### ISSUE TITLE
theme dark not respected

### ISSUE THREAD

**Issue by GreyXor** [modbender/nuxt-toastify#1]
Hello,
I added this into my nuxt.conf.ts
```ts
  toastify: {
    theme: "dark",
  },
```
and i'm using it like it
```ts
  useToastify("test", {
    type: "error",
  });
```
but I still get the light theme.

![image](https://github.com/user-attachments/assets/5edf2e71-7aa0-4351-b60d-72ad502385dd)

Any idea ?
Thanks

**Comment by modbender** [comment]
fixed in v0.0.2

**Comment by GreyXor** [comment]
> fixed in v0.0.2

@modbender thanks but are you sure ? I just tested and it's still light theme.

```ts
{
    "nuxt-toastify": "^0.0.2",
    "vue3-toastify": "^0.2.2",
}
```
![image](https://github.com/user-attachments/assets/0d920c20-a99a-4697-9db1-fc83eb4bbd47)

```ts
  toastify: {
    theme: "dark",
  },
```

**Comment by modbender** [comment]
It's working for me, also you do not need to install vue3-toastify separately.
You can test my demo here and verify for yourself if it's working or not.

https://stackblitz.com/github/modbender/nuxt-toastify?file=playground%2Fnuxt.config.ts

**Comment by GreyXor** [comment]
Thanks, that weird for me it's light and when I refresh 3 times it's dark. Maybe I have a PWA cache that's a bit strong, but it seems to work in some cases. Let's keep this issue closed and resolved because on a minimal project I don't have the issue, thank you for your responsiveness.
